package ui;

import data.GestorEntidades;
import java.util.ArrayList;
import static java.util.Objects.isNull;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Direccion;
import model.ExcursionCultural;
import model.GuiaTuristico;
import model.PaseoLacustre;
import model.Persistible;
import model.Persona;
import model.Rut;
import model.RutaGastronomica;
import model.ServicioTuristico;
import util.UtilCliente;
import util.UtilDireccion;
import util.UtilGuiaTuristico;
import util.UtilPersona;
import util.UtilRut;
import util.UtilServicioTuristico;

/**
 * Ventana que permite gestionar una entidad ya registrada: buscarla por nombre
 * o código de reserva
 */
public class FrameGestionar extends javax.swing.JFrame {
    private final GestorEntidades gestor;
    UtilPersona utilPersona = new UtilPersona();
    UtilDireccion utilDireccion = new UtilDireccion();
    UtilRut utilRut = new UtilRut();
    UtilGuiaTuristico utilGuia = new UtilGuiaTuristico();
    UtilCliente utilCliente = new UtilCliente();
    UtilServicioTuristico utilServicio = new UtilServicioTuristico();

    //Entidad encontrada actualmente y su posición dentro de la colección
    private Persistible entidadActual;
    private int indiceActual = -1;

    //Resultados de la última búsqueda y posición actual dentro de ellos, para navegar con las flechas
    private ArrayList<Persistible> resultadosBusqueda = new ArrayList<>();
    private int indiceResultado = -1;

    /**
     * Crea la ventana de gestión de entidades.
     * @param gestorEntidades: gestor sobre el que se buscará, actualizará o eliminará.
     */
    public FrameGestionar(GestorEntidades gestorEntidades) {
        this.gestor = gestorEntidades;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        btnAnterior.setVisible(false);
        btnSiguiente.setVisible(false);
        labelResultado.setVisible(false);
        ocultarCamposDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        labelBuscarPor = new javax.swing.JLabel();
        comboBoxBuscar = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        labelTipo = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        labelNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        labelRut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        labelDuracion = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        labelCapacidad = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        labelCalle = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        labelComuna = new javax.swing.JLabel();
        txtComuna = new javax.swing.JTextField();
        labelCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        labelVariable = new javax.swing.JLabel();
        txtVariable = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar entidad");

        labelTitulo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        labelTitulo.setText("Gestionar Entidad");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar y editar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

        labelBuscarPor.setText("Buscar por");

        comboBoxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Rut", "Código Reserva" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        labelTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTipo.setText("Tipo: -");

        btnAnterior.setText("◀");
        btnAnterior.addActionListener(this::btnAnteriorActionPerformed);

        labelResultado.setText("1 / 1");

        btnSiguiente.setText("▶");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);

        labelNombre.setText("Nombre");

        labelEdad.setText("Edad");

        labelRut.setText("Rut");

        labelDuracion.setText("Duración hrs");

        labelCapacidad.setText("Capacidad");

        labelCalle.setText("Calle");

        labelNumero.setText("Número");

        labelComuna.setText("Comuna");

        labelCiudad.setText("Ciudad");

        labelVariable.setText("Dato adicional");

        jLayeredPane1.setLayer(labelBuscarPor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comboBoxBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnAnterior, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelResultado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnSiguiente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelEdad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtEdad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelRut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtRut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelDuracion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtDuracion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelCapacidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCapacidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelCalle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCalle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelComuna, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtComuna, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelCiudad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCiudad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelVariable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtVariable, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(labelTipo)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(labelBuscarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNombre)
                            .addComponent(labelEdad)
                            .addComponent(labelRut)
                            .addComponent(labelDuracion)
                            .addComponent(labelCapacidad)
                            .addComponent(labelCalle)
                            .addComponent(labelNumero)
                            .addComponent(labelComuna)
                            .addComponent(labelCiudad)
                            .addComponent(labelVariable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtEdad)
                            .addComponent(txtRut)
                            .addComponent(txtDuracion)
                            .addComponent(txtCapacidad)
                            .addComponent(txtCalle)
                            .addComponent(txtNumero)
                            .addComponent(txtComuna)
                            .addComponent(txtCiudad)
                            .addComponent(txtVariable))))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBuscarPor)
                    .addComponent(comboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(labelResultado)
                    .addComponent(btnSiguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuracion)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCapacidad)
                    .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCalle)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComuna)
                    .addComponent(txtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCiudad)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVariable)
                    .addComponent(txtVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelTitulo)
                    .addComponent(jLayeredPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrar))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Busca la entidad según el criterio y el texto ingresados, y muestra la
     * primera coincidencia en el formulario correspondiente. Si la búsqueda por
     * nombre encuentra más de una entidad, habilita las flechas de navegación
     * e informa la cantidad de resultados encontrados.
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String criterio = comboBoxBuscar.getSelectedItem().toString();
        String texto = txtBuscar.getText().strip().trim();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar un valor para buscar", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ArrayList<Persistible> encontradas;
        if (criterio.equals("Código Reserva")) {
            encontradas = comoLista(gestor.buscarXCodigoReserva(texto));
        } else if (criterio.equals("Rut")) {
            encontradas = comoLista(gestor.buscarXRut(texto));
        } else {
            encontradas = gestor.buscarTodosXNombre(texto);
        }

        if (encontradas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna entidad\ncon los datos proporcionados", "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
            limpiarSeleccion();
            return;
        }

        resultadosBusqueda = encontradas;
        indiceResultado = 0;
        mostrarResultadoActual();

        if (encontradas.size() > 1) {
            JOptionPane.showMessageDialog(this, "Se han encontrado " + encontradas.size() + " entidades con ese nombre, utilice las flechas para navegar.", "Resultados encontrados", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * Envuelve un resultado de búsqueda exacta (Rut o Código Reserva) en una
     * lista, para poder reutilizar el mismo flujo de navegación que la
     * búsqueda por nombre.
     * @param entidadEncontrada: entidad encontrada, o null si no hubo coincidencia.
     * @return una lista con la entidad, o vacía si encontrada es null.
     */
    private ArrayList<Persistible> comoLista(Persistible entidadEncontrada) {
        var lista = new ArrayList<Persistible>();
        if (entidadEncontrada != null) {
            lista.add(entidadEncontrada);
        }
        return lista;
    }

    /**
     * Retrocede al resultado anterior de la búsqueda actual, volviendo al
     * último resultado si ya se estaba en el primero.
     */
    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        indiceResultado = (indiceResultado - 1 + resultadosBusqueda.size()) % resultadosBusqueda.size();
        mostrarResultadoActual();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    /**
     * Avanza al siguiente resultado de la búsqueda actual, volviendo al
     * primer resultado si ya se estaba en el último.
     */
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        indiceResultado = (indiceResultado + 1) % resultadosBusqueda.size();
        mostrarResultadoActual();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * Muestra en el formulario el resultado ubicado en indiceResultado dentro
     * de resultadosBusqueda, y actualiza el estado de las flechas de navegación.
     */
    private void mostrarResultadoActual() {
        Persistible entidadEncontrada = resultadosBusqueda.get(indiceResultado);
        entidadActual = entidadEncontrada;
        indiceActual = gestor.indiceDe(entidadEncontrada);

        if (entidadEncontrada instanceof Persona) {
            mostrarPersona((Persona) entidadEncontrada);
        } else if (entidadEncontrada instanceof ServicioTuristico) {
            mostrarServicio((ServicioTuristico) entidadEncontrada);
        }

        actualizarNavegacion();
    }

    /**
     * Muestra u oculta las flechas de navegación y el contador de resultados
     * según la cantidad de coincidencias de la última búsqueda: solo se
     * muestran cuando hay más de una entidad encontrada.
     */
    private void actualizarNavegacion() {
        boolean hayVarios = resultadosBusqueda.size() > 1;
        btnAnterior.setVisible(hayVarios);
        btnSiguiente.setVisible(hayVarios);
        labelResultado.setVisible(hayVarios);
        if (hayVarios) {
            labelResultado.setText((indiceResultado + 1) + " / " + resultadosBusqueda.size());
        }
        pack();
    }

    /**
     * Reconstruye la entidad seleccionada con los datos del formulario y la
     * actualiza en el gestor. Esto según el tipo real de la entidad.
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (isNull(entidadActual)) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar una entidad", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (entidadActual instanceof Cliente) {
            actualizarCliente();
        } else if (entidadActual instanceof GuiaTuristico) {
            actualizarGuia();
        } else if (entidadActual instanceof ServicioTuristico) {
            actualizarServicio();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * Elimina la entidad seleccionada previa confirmación del usuario.
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (isNull(entidadActual)) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar una entidad", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar la entidad seleccionada?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            gestor.eliminar(indiceActual);
            JOptionPane.showMessageDialog(this, "Entidad eliminada con éxito", "Correcto", JOptionPane.INFORMATION_MESSAGE);
            limpiarSeleccion();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * Rellena el formulario con los datos del cliente o guía hallado y muestra
     * únicamente los campos correspondientes a una persona.
     * @param persona: persona encontrada a mostrar.
     */
    private void mostrarPersona(Persona persona) {
        txtNombre.setText(persona.getNombre());
        txtEdad.setText(String.valueOf(persona.getEdad()));
        txtRut.setText(persona.getRut().toString());

        Direccion direccion = persona.getDireccion();
        txtCalle.setText(direccion.getCalle());
        txtNumero.setText(String.valueOf(direccion.getNumero()));
        txtComuna.setText(direccion.getComuna());
        txtCiudad.setText(direccion.getCiudad());

        if (persona instanceof Cliente) {
            labelTipo.setText("Tipo: Cliente");
            labelVariable.setText("Cód. Reserva");
            txtVariable.setText(((Cliente) persona).getCodigoReserva());
            //El código de reserva se conserva, no se edita manualmente
            txtVariable.setEditable(false);
        } else if (persona instanceof GuiaTuristico) {
            labelTipo.setText("Tipo: Guía Turístico");
            labelVariable.setText("Especialidad");
            txtVariable.setText(((GuiaTuristico) persona).getEspecialidad());
            txtVariable.setEditable(true);
        }

        mostrarCamposPersona();
    }

    /**
     * Rellena el formulario con los datos del servicio hallado y muestra
     * únicamente los campos correspondientes a un servicio, adaptando el campo
     * variable al subtipo.
     * @param servicio: servicio turístico encontrado a mostrar.
     */
    private void mostrarServicio(ServicioTuristico servicio) {
        txtNombre.setText(servicio.getNombre());
        txtDuracion.setText(String.valueOf(servicio.getDuracionHoras()));
        txtCapacidad.setText(String.valueOf(servicio.getCapacidad()));
        txtVariable.setEditable(true);

        if (servicio instanceof RutaGastronomica) {
            labelTipo.setText("Tipo: Ruta Gastronómica");
            labelVariable.setText("Nro. Paradas");
            txtVariable.setText(String.valueOf(((RutaGastronomica) servicio).getNumeroDeParadas()));
        } else if (servicio instanceof PaseoLacustre) {
            labelTipo.setText("Tipo: Paseo Lacustre");
            labelVariable.setText("Tipo Embarcación");
            txtVariable.setText(((PaseoLacustre) servicio).getTipoEmbarcacion());
        } else if (servicio instanceof ExcursionCultural) {
            labelTipo.setText("Tipo: Excursión Cultural");
            labelVariable.setText("Lugar Histórico");
            txtVariable.setText(((ExcursionCultural) servicio).getLugarHistorico());
        }

        mostrarCamposServicio();
    }

    /**
     * Valida los campos de persona y devuelve una Dirección válida, o null si
     * algún dato es incorrecto (los validadores ya informan el error).
     * @return la Dirección construida, o null si la validación falla.
     */
    private Direccion validarDatosPersona() {
        String nombre = txtNombre.getText().strip();
        String edad = txtEdad.getText().strip();
        String calle = txtCalle.getText().strip();
        String numero = txtNumero.getText().strip();
        String comuna = txtComuna.getText().strip();
        String ciudad = txtCiudad.getText().strip();
        String rut = txtRut.getText().strip();

        if (!utilPersona.validarNombre(nombre)) {
            return null;
        }
        if (!utilPersona.esEntero(edad) || !utilPersona.validarEdad(edad)) {
            return null;
        }
        if (!utilDireccion.validarCalle(calle)) {
            return null;
        }
        if (!utilDireccion.esEntero(numero) || !utilDireccion.validarNumeracion(numero)) {
            return null;
        }
        if (!utilDireccion.validarComuna(comuna)) {
            return null;
        }
        if (!utilDireccion.validarCiudad(ciudad)) {
            return null;
        }
        if (!utilRut.validarRut(rut)) {
            return null;
        }
        return new Direccion(calle, numero, comuna, ciudad);
    }

    /**
     * Reconstruye y actualiza un cliente conservando su código de reserva.
     */
    private void actualizarCliente() {
        Direccion direccion = validarDatosPersona();
        if (isNull(direccion)) {
            return;
        }
        String codigo = txtVariable.getText().strip();
        if (!utilCliente.validarCodigo(codigo)) {
            return;
        }
        Rut rut = new Rut(txtRut.getText().strip().strip());
        Cliente cliente = new Cliente(txtNombre.getText().strip(), txtEdad.getText().strip(), direccion, rut, codigo);
        gestor.actualizar(cliente, indiceActual);
        entidadActual = cliente;
        JOptionPane.showMessageDialog(this, "Cliente actualizado con éxito", "Correcto", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Reconstruye y actualiza un guía turístico validando su especialidad.
     */
    private void actualizarGuia() {
        Direccion direccion = validarDatosPersona();
        if (isNull(direccion)) {
            return;
        }
        String especialidad = txtVariable.getText().strip();
        if (!utilGuia.validarEspecialidad(especialidad)) {
            return;
        }
        Rut rut = new Rut(txtRut.getText().strip());
        GuiaTuristico guia = new GuiaTuristico(txtNombre.getText().strip(), txtEdad.getText().strip(), direccion, rut, especialidad);
        gestor.actualizar(guia, indiceActual);
        entidadActual = guia;
        JOptionPane.showMessageDialog(this, "Guía actualizado con éxito", "Correcto", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Reconstruye y actualiza un servicio turístico según su subtipo real.
     */
    private void actualizarServicio() {
        String nombre = txtNombre.getText().strip();
        String duracion = txtDuracion.getText().strip();
        String capacidad = txtCapacidad.getText().strip();
        String variable = txtVariable.getText().strip();

        if (!utilServicio.esDouble(duracion)) {
            return;
        }
        if (!utilServicio.esEntero(capacidad) || !utilServicio.validarCapacidad(capacidad)) {
            return;
        }

        ServicioTuristico nuevo;
        if (entidadActual instanceof RutaGastronomica) {
            if (!utilServicio.esEntero(variable)) {
                return;
            }
            nuevo = new RutaGastronomica(nombre, duracion, capacidad, variable);
        } else if (entidadActual instanceof PaseoLacustre) {
            nuevo = new PaseoLacustre(nombre, duracion, capacidad, variable);
        } else {
            nuevo = new ExcursionCultural(nombre, duracion, capacidad, variable);
        }

        if (!utilServicio.validarServicio(nuevo)) {
            return;
        }
        gestor.actualizar(nuevo, indiceActual);
        entidadActual = nuevo;
        JOptionPane.showMessageDialog(this, "Servicio actualizado con éxito", "Correcto", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Muestra los campos propios de una persona y oculta los de servicio.
     */
    private void mostrarCamposPersona() {
        setCamposPersonaVisibles(true);
        labelDuracion.setVisible(false);
        txtDuracion.setVisible(false);
        labelCapacidad.setVisible(false);
        txtCapacidad.setVisible(false);
        labelVariable.setVisible(true);
        txtVariable.setVisible(true);
        pack();
    }

    /**
     * Muestra los campos propios de un servicio y oculta los de persona.
     */
    private void mostrarCamposServicio() {
        setCamposPersonaVisibles(false);
        labelDuracion.setVisible(true);
        txtDuracion.setVisible(true);
        labelCapacidad.setVisible(true);
        txtCapacidad.setVisible(true);
        labelVariable.setVisible(true);
        txtVariable.setVisible(true);
        pack();
    }

    /**
     * Oculta todos los campos de datos, dejando solo la barra de búsqueda.
     */
    private void ocultarCamposDatos() {
        setCamposPersonaVisibles(false);
        labelDuracion.setVisible(false);
        txtDuracion.setVisible(false);
        labelCapacidad.setVisible(false);
        txtCapacidad.setVisible(false);
        labelVariable.setVisible(false);
        txtVariable.setVisible(false);
        pack();
    }

    /**
     * Activa o desactiva la visibilidad de los campos exclusivos de una persona
     * (edad, rut y dirección), que se comparten entre clientes y guías.
     * @param visible: true para mostrarlos, false para ocultarlos.
     */
    private void setCamposPersonaVisibles(boolean visible) {
        labelNombre.setVisible(true);
        txtNombre.setVisible(true);
        labelEdad.setVisible(visible);
        txtEdad.setVisible(visible);
        labelRut.setVisible(visible);
        txtRut.setVisible(visible);
        labelCalle.setVisible(visible);
        txtCalle.setVisible(visible);
        labelNumero.setVisible(visible);
        txtNumero.setVisible(visible);
        labelComuna.setVisible(visible);
        txtComuna.setVisible(visible);
        labelCiudad.setVisible(visible);
        txtCiudad.setVisible(visible);
    }

    /**
     * Restablece la selección actual, la navegación entre resultados y oculta
     * el formulario de datos.
     */
    private void limpiarSeleccion() {
        entidadActual = null;
        indiceActual = -1;
        resultadosBusqueda = new ArrayList<>();
        indiceResultado = -1;
        labelTipo.setText("Tipo: -");
        btnAnterior.setVisible(false);
        btnSiguiente.setVisible(false);
        labelResultado.setVisible(false);
        ocultarCamposDatos();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> comboBoxBuscar;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBuscarPor;
    private javax.swing.JLabel labelCalle;
    private javax.swing.JLabel labelCapacidad;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelComuna;
    private javax.swing.JLabel labelDuracion;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelRut;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVariable;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtComuna;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtVariable;
    // End of variables declaration//GEN-END:variables
}
