package ui;

import data.GestorEntidades;
import java.util.ArrayList;
import static java.util.Objects.isNull;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Reserva;
import model.ServicioTuristico;
import util.UtilReserva;

/**
 * Ventana que permite gestionar las reservas: crear nuevas reservas (asociando un
 * cliente con un servicio turístico y descontando cupos de su capacidad) y buscar,
 * actualizar o eliminar reservas existentes. Sigue el estilo de FrameGestionar.
 */
public class FrameGestionarReservas extends javax.swing.JFrame {
    private final GestorEntidades gestor;
    private final UtilReserva utilReserva = new UtilReserva();

    //Clientes y servicios que se muestran en los combos. Se guardan en estas listas
    //porque los combos solo muestran texto, así la posición elegida en el combo
    //corresponde a la misma posición de la lista.
    private ArrayList<Cliente> clientes = new ArrayList<>();
    private ArrayList<ServicioTuristico> servicios = new ArrayList<>();

    //Reserva seleccionada actualmente en la sección de gestión y su posición
    private Reserva reservaActual;
    private int indiceActual = -1;

    //Resultados de la última búsqueda y posición actual, para navegar con las flechas
    private ArrayList<Reserva> resultadosBusqueda = new ArrayList<>();
    private int indiceResultado = -1;

    /**
     * Crea la ventana de gestión de reservas.
     * @param gestorEntidades: gestor sobre el que se crearán, buscarán, actualizarán o eliminarán reservas.
     */
    public FrameGestionarReservas(GestorEntidades gestorEntidades) {
        this.gestor = gestorEntidades;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        cargarComboBox();
        mostrarCodigoCliente();
        actualizarCuposCrear();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        panelCrear = new javax.swing.JPanel();
        labelTxtCliente = new javax.swing.JLabel();
        comboBoxCliente = new javax.swing.JComboBox<>();
        labelTxtServicio = new javax.swing.JLabel();
        comboBoxServicio = new javax.swing.JComboBox<>();
        labelTxtCupos = new javax.swing.JLabel();
        labelCuposCrear = new javax.swing.JLabel();
        labelTxtIntegrantes = new javax.swing.JLabel();
        txtIntegrantesCrear = new javax.swing.JTextField();
        labelTxtCodigo = new javax.swing.JLabel();
        txtCodigoCrear = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        panelGestionar = new javax.swing.JPanel();
        labelBuscarPor = new javax.swing.JLabel();
        comboBuscar = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        labelTxtCodigoSel = new javax.swing.JLabel();
        labelCodigoSel = new javax.swing.JLabel();
        labelTxtClienteSel = new javax.swing.JLabel();
        labelClienteSel = new javax.swing.JLabel();
        labelTxtServicioSel = new javax.swing.JLabel();
        labelServicioSel = new javax.swing.JLabel();
        labelTxtCuposSel = new javax.swing.JLabel();
        labelCuposSel = new javax.swing.JLabel();
        labelTxtIntegrantesSel = new javax.swing.JLabel();
        txtIntegrantesSel = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar reservas");

        labelTitulo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        labelTitulo.setText("Gestionar Reservas");

        panelCrear.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear reserva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

        labelTxtCliente.setText("Cliente");

        comboBoxCliente.addActionListener(this::comboBoxClienteActionPerformed);

        labelTxtServicio.setText("Servicio");

        comboBoxServicio.addActionListener(this::comboBoxServicioActionPerformed);

        labelTxtCupos.setText("Cupos disponibles");

        labelCuposCrear.setText("-");

        labelTxtIntegrantes.setText("N° integrantes");

        labelTxtCodigo.setText("Código");

        txtCodigoCrear.setEditable(false);

        btnCrear.setText("Crear reserva");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTxtCliente)
                            .addComponent(labelTxtServicio)
                            .addComponent(labelTxtCupos)
                            .addComponent(labelTxtIntegrantes)
                            .addComponent(labelTxtCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxCliente, 0, 240, Short.MAX_VALUE)
                            .addComponent(comboBoxServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCuposCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIntegrantesCrear)
                            .addComponent(txtCodigoCrear)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCrear)))
                .addContainerGap())
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtCliente)
                    .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtServicio)
                    .addComponent(comboBoxServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtCupos)
                    .addComponent(labelCuposCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtIntegrantes)
                    .addComponent(txtIntegrantesCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtCodigo)
                    .addComponent(txtCodigoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrear)
                .addContainerGap())
        );

        panelGestionar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar y gestionar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

        labelBuscarPor.setText("Buscar por");

        comboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código Reserva", "Nombre Cliente" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnAnterior.setText("◀");
        btnAnterior.addActionListener(this::btnAnteriorActionPerformed);

        labelResultado.setText("1 / 1");

        btnSiguiente.setText("▶");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);

        labelTxtCodigoSel.setText("Código");

        labelCodigoSel.setText("-");

        labelTxtClienteSel.setText("Cliente");

        labelClienteSel.setText("-");

        labelTxtServicioSel.setText("Servicio");

        labelServicioSel.setText("-");

        labelTxtCuposSel.setText("Cupos disponibles");

        labelCuposSel.setText("-");

        labelTxtIntegrantesSel.setText("N° integrantes");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout panelGestionarLayout = new javax.swing.GroupLayout(panelGestionar);
        panelGestionar.setLayout(panelGestionarLayout);
        panelGestionarLayout.setHorizontalGroup(
            panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(panelGestionarLayout.createSequentialGroup()
                        .addComponent(labelBuscarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(panelGestionarLayout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente))
                    .addGroup(panelGestionarLayout.createSequentialGroup()
                        .addGroup(panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTxtCodigoSel)
                            .addComponent(labelTxtClienteSel)
                            .addComponent(labelTxtServicioSel)
                            .addComponent(labelTxtCuposSel)
                            .addComponent(labelTxtIntegrantesSel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCodigoSel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelClienteSel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelServicioSel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCuposSel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIntegrantesSel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestionarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addContainerGap())
        );
        panelGestionarLayout.setVerticalGroup(
            panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBuscarPor)
                    .addComponent(comboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(labelResultado)
                    .addComponent(btnSiguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtCodigoSel)
                    .addComponent(labelCodigoSel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtClienteSel)
                    .addComponent(labelClienteSel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtServicioSel)
                    .addComponent(labelServicioSel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtCuposSel)
                    .addComponent(labelCuposSel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtIntegrantesSel)
                    .addComponent(txtIntegrantesSel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelTitulo)
                    .addComponent(panelCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGestionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(10, 10, 10)
                .addComponent(panelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Actualiza los cupos mostrados cada vez que se cambia el servicio elegido
     * en la sección de creación.
     */
    private void comboBoxServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxServicioActionPerformed
        actualizarCuposCrear();
    }//GEN-LAST:event_comboBoxServicioActionPerformed

    /**
     * Crea una nueva reserva con el cliente y servicio seleccionados, validando
     * la cantidad de integrantes y los cupos disponibles del servicio.
     */
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Cliente cliente = obtenerClienteElegido();
        ServicioTuristico servicio = obtenerServicioElegido();

        if (isNull(cliente) || isNull(servicio)) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente y un servicio", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (gestor.reservasLlenas()) {
            JOptionPane.showMessageDialog(this, "Se alcanzó el máximo de 40 reservas permitidas", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String integrantes = txtIntegrantesCrear.getText().strip();

        if (!utilReserva.esEntero(integrantes) || !utilReserva.validarCantidadIntegrantes(integrantes)) {
            return;
        }

        int cantidad = Integer.parseInt(integrantes);
        int cupos = gestor.cuposDisponibles(servicio, null);
        if (cantidad > cupos) {
            JOptionPane.showMessageDialog(this, "El servicio solo tiene " + cupos + " cupos disponibles", "Sin cupos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //La reserva se crea con el código que tiene asignado el cliente elegido
        Reserva reserva = new Reserva(cliente.getCodigoReserva(), cliente, servicio, integrantes);
        gestor.agregarReserva(reserva);
        JOptionPane.showMessageDialog(this, "Reserva creada con éxito", "Correcto", JOptionPane.INFORMATION_MESSAGE);
        txtIntegrantesCrear.setText("");
        actualizarCuposCrear();
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * Busca las reservas según el criterio y el texto ingresados, y muestra la
     * primera coincidencia. Si hay más de un resultado, habilita las flechas de
     * navegación e informa la cantidad encontrada.
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String criterio = comboBuscar.getSelectedItem().toString();
        String texto = txtBuscar.getText().strip().trim();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un valor para buscar", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ArrayList<Reserva> encontradas;
        if (criterio.equals("Código Reserva")) {
            encontradas = gestor.buscarReservasXCodigo(texto);
        } else {
            encontradas = gestor.buscarReservasXNombreCliente(texto);
        }

        if (encontradas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna reserva\ncon los datos proporcionados", "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
            return;
        }

        resultadosBusqueda = encontradas;
        indiceResultado = 0;
        mostrarResultadoActual();

        if (encontradas.size() > 1) {
            JOptionPane.showMessageDialog(this, "Se encontraron " + encontradas.size() + " reservas, utilice las flechas para navegar.", "Resultados encontrados", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * Retrocede al resultado anterior de la búsqueda actual, volviendo al
     * último resultado si ya se estaba en el primero.
     */
    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (resultadosBusqueda.isEmpty()) {
            return;
        }
        indiceResultado = (indiceResultado - 1 + resultadosBusqueda.size()) % resultadosBusqueda.size();
        mostrarResultadoActual();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    /**
     * Avanza al siguiente resultado de la búsqueda actual, volviendo al primer
     * resultado si ya se estaba en el último.
     */
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (resultadosBusqueda.isEmpty()) {
            return;
        }
        indiceResultado = (indiceResultado + 1) % resultadosBusqueda.size();
        mostrarResultadoActual();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * Actualiza la cantidad de integrantes de la reserva seleccionada,
     * respetando los cupos disponibles del servicio asociado.
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (isNull(reservaActual)) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar una reserva", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String integrantes = txtIntegrantesSel.getText().strip();
        if (!utilReserva.esEntero(integrantes) || !utilReserva.validarCantidadIntegrantes(integrantes)) {
            return;
        }
        int cantidad = Integer.parseInt(integrantes);
        int cuposMax = gestor.cuposDisponibles(reservaActual.getServicio(), reservaActual);
        if (cantidad > cuposMax) {
            JOptionPane.showMessageDialog(this, "El servicio solo admite " + cuposMax + " integrantes para esta reserva", "Sin cupos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Reserva actualizada = new Reserva(reservaActual.getCodigoReserva(), reservaActual.getCliente(), reservaActual.getServicio(), integrantes);
        gestor.actualizarReserva(actualizada, indiceActual);
        reservaActual = actualizada;
        resultadosBusqueda.set(indiceResultado, actualizada);
        JOptionPane.showMessageDialog(this, "Reserva actualizada con éxito", "Correcto", JOptionPane.INFORMATION_MESSAGE);
        actualizarCuposCrear();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * Elimina la reserva seleccionada previa confirmación del usuario.
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (isNull(reservaActual)) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar una reserva", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar la reserva seleccionada?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            gestor.eliminarReserva(indiceActual);
            JOptionPane.showMessageDialog(this, "Reserva eliminada con éxito", "Correcto", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
            actualizarCuposCrear();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * Muestra el código de reserva del cliente elegido cada vez que se cambia la
     * selección en la sección de creación.
     */
    private void comboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxClienteActionPerformed
        mostrarCodigoCliente();
    }//GEN-LAST:event_comboBoxClienteActionPerformed

    /**
     * Carga los combos de clientes y servicios desde el gestor. Los combos solo
     * muestran texto, por lo que además se guardan las listas de objetos para
     * poder recuperar el cliente o el servicio elegido según su posición.
     * Si falta alguno, deshabilita la creación de reservas.
     */
    private void cargarComboBox() {
        comboBoxCliente.removeAllItems();
        comboBoxServicio.removeAllItems();
        clientes = gestor.obtenerClientes();
        servicios = gestor.obtenerServicios();

        for (Cliente cliente : clientes) {
            comboBoxCliente.addItem(cliente.getNombre() + " - " + cliente.getRut().toString());
        }
        for (ServicioTuristico servicio : servicios) {
            comboBoxServicio.addItem(servicio.getNombre() + " (cap. " + servicio.getCapacidad() + ")");
        }

        boolean puedeCrear = comboBoxCliente.getItemCount() > 0 && comboBoxServicio.getItemCount() > 0;
        btnCrear.setEnabled(puedeCrear);
        if (!puedeCrear) {
            labelCuposCrear.setText("Debe existir al menos un cliente y un servicio");
        }
    }

    /**
     * Obtiene el cliente que está elegido en el combo, usando su posición.
     * @return el cliente seleccionado, o null si el combo está vacío.
     */
    private Cliente obtenerClienteElegido() {
        int posicion = comboBoxCliente.getSelectedIndex();
        if (posicion < 0) {
            return null;
        }
        return clientes.get(posicion);
    }

    /**
     * Obtiene el servicio que está elegido en el combo, usando su posición.
     * @return el servicio seleccionado, o null si el combo está vacío.
     */
    private ServicioTuristico obtenerServicioElegido() {
        int posicion = comboBoxServicio.getSelectedIndex();
        if (posicion < 0) {
            return null;
        }
        return servicios.get(posicion);
    }

    /**
     * Muestra en el formulario el código de reserva del cliente elegido, ya que
     * la reserva se crea con el código que ese cliente tiene asignado.
     */
    private void mostrarCodigoCliente() {
        Cliente cliente = obtenerClienteElegido();
        if (isNull(cliente)) {
            txtCodigoCrear.setText("");
            return;
        }
        txtCodigoCrear.setText(cliente.getCodigoReserva());
    }

    /**
     * Actualiza la etiqueta de cupos disponibles del servicio seleccionado en la creación.
     */
    private void actualizarCuposCrear() {
        ServicioTuristico servicio = obtenerServicioElegido();
        if (isNull(servicio)) {
            return;
        }
        int cupos = gestor.cuposDisponibles(servicio, null);
        labelCuposCrear.setText(cupos + " de " + servicio.getCapacidad());
    }

    /**
     * Muestra en el formulario la reserva ubicada en indiceResultado dentro de
     * resultadosBusqueda, y actualiza el estado de las flechas de navegación.
     */
    private void mostrarResultadoActual() {
        reservaActual = resultadosBusqueda.get(indiceResultado);
        indiceActual = gestor.indiceDeReserva(reservaActual);

        labelCodigoSel.setText(reservaActual.getCodigoReserva());
        labelClienteSel.setText(reservaActual.getCliente().getNombre() + " (" + reservaActual.getCliente().getRut().toString() + ")");
        labelServicioSel.setText(reservaActual.getServicio().getNombre());
        int cuposMax = gestor.cuposDisponibles(reservaActual.getServicio(), reservaActual);
        labelCuposSel.setText("Máximo " + cuposMax + " (capacidad " + reservaActual.getServicio().getCapacidad() + ")");
        txtIntegrantesSel.setText(String.valueOf(reservaActual.getCantidadIntegrantes()));

        actualizarInfoFrame();
    }

    /**
     * Muestra u oculta las flechas de navegación y el contador de resultados
     * según la cantidad de coincidencias de la última búsqueda: solo se
     * muestran cuando hay más de una reserva encontrada.
     */
    private void actualizarInfoFrame() {
        boolean hayVarios = resultadosBusqueda.size() > 1;
        btnAnterior.setVisible(hayVarios);
        btnSiguiente.setVisible(hayVarios);
        labelResultado.setVisible(hayVarios);
        if (hayVarios) {
            labelResultado.setText((indiceResultado + 1) + " / " + resultadosBusqueda.size());
        }
        pack();
    }

    /**
     * Restablece la selección actual y la navegación entre resultados.
     */
    private void limpiar() {
        reservaActual = null;
        indiceActual = -1;
        resultadosBusqueda = new ArrayList<>();
        indiceResultado = -1;
        labelCodigoSel.setText("-");
        labelClienteSel.setText("-");
        labelServicioSel.setText("-");
        labelCuposSel.setText("-");
        txtIntegrantesSel.setText("");
        btnAnterior.setVisible(false);
        btnSiguiente.setVisible(false);
        labelResultado.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> comboBoxCliente;
    private javax.swing.JComboBox<String> comboBoxServicio;
    private javax.swing.JComboBox<String> comboBuscar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBuscarPor;
    private javax.swing.JLabel labelClienteSel;
    private javax.swing.JLabel labelCodigoSel;
    private javax.swing.JLabel labelCuposCrear;
    private javax.swing.JLabel labelCuposSel;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelServicioSel;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTxtCliente;
    private javax.swing.JLabel labelTxtClienteSel;
    private javax.swing.JLabel labelTxtCodigo;
    private javax.swing.JLabel labelTxtCodigoSel;
    private javax.swing.JLabel labelTxtCupos;
    private javax.swing.JLabel labelTxtCuposSel;
    private javax.swing.JLabel labelTxtIntegrantes;
    private javax.swing.JLabel labelTxtIntegrantesSel;
    private javax.swing.JLabel labelTxtServicio;
    private javax.swing.JLabel labelTxtServicioSel;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JPanel panelGestionar;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigoCrear;
    private javax.swing.JTextField txtIntegrantesCrear;
    private javax.swing.JTextField txtIntegrantesSel;
    // End of variables declaration//GEN-END:variables
}
