package ui;

import data.GestorEntidades;
import model.Direccion;
import model.GuiaTuristico;
import util.UtilDireccion;
import util.UtilGuiaTuristico;
import javax.swing.JOptionPane;

/**
 * Ventana que permite ingresar un nuevo guía turístico (nombre, edad y dirección)
y agregarlo al GestorEntidades recibido desde la ventana principal.
 */
public class FrameIngresarGuia extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameIngresarGuia.class.getName());
    private final GestorEntidades gestor;
    UtilDireccion utilDireccion  = new UtilDireccion();
    UtilGuiaTuristico utilGuia  = new UtilGuiaTuristico();
    /**
     * Crea la ventana de ingreso de guía turístico.
     * @param gestorEntidades: gestor donde se agregará el guía creado.
     */
    public FrameIngresarGuia(GestorEntidades gestorEntidades) {
        initComponents();
        this.gestor = gestorEntidades;
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPane1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        btnAgregarGuia = new javax.swing.JButton();
        btnCerrarGuia = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        labelNombreGuia = new javax.swing.JLabel();
        labelEdadGuia = new javax.swing.JLabel();
        labelCalleGuia = new javax.swing.JLabel();
        labelNumeracionGuia = new javax.swing.JLabel();
        labelComunaGuia = new javax.swing.JLabel();
        labelCiudadGuia = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtCalleGuia = new javax.swing.JTextField();
        txtNombreGuia = new javax.swing.JTextField();
        txtNumeracionGuia = new javax.swing.JTextField();
        txtCiudadGuia = new javax.swing.JTextField();
        txtEdadGuia = new javax.swing.JTextField();
        txtComunaGuia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        labelTitulo.setText("Nuevo Guía");

        btnAgregarGuia.setText("Agregar");
        btnAgregarGuia.addActionListener(this::btnAgregarGuiaActionPerformed);

        btnCerrarGuia.setText("Cerrar");
        btnCerrarGuia.addActionListener(this::btnCerrarGuiaActionPerformed);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Guía", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

        labelNombreGuia.setText("Nombre");

        labelEdadGuia.setText("Edad");

        labelCalleGuia.setText("Calle");

        labelNumeracionGuia.setText("Número");

        labelComunaGuia.setText("Comuna");

        labelCiudadGuia.setText("Ciudad");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setText("Dirección");

        txtCalleGuia.addActionListener(this::txtCalleGuiaActionPerformed);

        txtNombreGuia.addActionListener(this::txtNombreGuiaActionPerformed);

        txtNumeracionGuia.addActionListener(this::txtNumeracionGuiaActionPerformed);

        txtCiudadGuia.addActionListener(this::txtCiudadGuiaActionPerformed);

        txtEdadGuia.addActionListener(this::txtEdadGuiaActionPerformed);

        txtComunaGuia.addActionListener(this::txtComunaGuiaActionPerformed);

        jLayeredPane1.setLayer(labelNombreGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelEdadGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelCalleGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelNumeracionGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelComunaGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelCiudadGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCalleGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNombreGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNumeracionGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCiudadGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtEdadGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtComunaGuia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelComunaGuia)
                                .addComponent(labelNombreGuia)
                                .addComponent(labelEdadGuia, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(labelCalleGuia))
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(labelCiudadGuia)))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 5, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreGuia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCalleGuia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCiudadGuia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(txtEdadGuia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(txtComunaGuia, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(labelNumeracionGuia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumeracionGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreGuia))
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdadGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEdadGuia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(9, 9, 9)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCalleGuia)
                    .addComponent(txtCalleGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeracionGuia)
                    .addComponent(txtNumeracionGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComunaGuia)
                    .addComponent(txtComunaGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCiudadGuia)
                    .addComponent(txtCiudadGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPane1Layout = new javax.swing.GroupLayout(JPane1);
        JPane1.setLayout(JPane1Layout);
        JPane1Layout.setHorizontalGroup(
            JPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPane1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarGuia)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrarGuia)))
                .addContainerGap())
        );
        JPane1Layout.setVerticalGroup(
            JPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarGuia)
                    .addComponent(btnAgregarGuia))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarGuiaActionPerformed
        
            String calle = txtCalleGuia.getText();
            String comuna = txtComunaGuia.getText();
            String ciudad = txtCiudadGuia.getText();
            String numero = txtNumeracionGuia.getText();  
            String nombre = txtNombreGuia.getText();
            String edad = txtEdadGuia.getText();
            if(!utilGuia.validarNombre(nombre)){
                return;
            }
            if(!utilGuia.esEntero(edad) || !utilGuia.validarEdad(edad)){
                return;
            }                
            if(!utilDireccion.validarCalle(calle)){
                return;
            }
            if(!utilDireccion.esEntero(numero) || !utilDireccion.validarNumeracion(numero)){
                return;
            }            
            if(!utilDireccion.validarComuna(comuna)){
                return;
            }           
            if(!utilDireccion.validarCiudad(ciudad)){
                return;
            }
            var direccion = new Direccion(calle, numero, comuna, ciudad);
            var guia = new GuiaTuristico(nombre, edad, direccion);            
            gestor.agregar(guia);
            limpiar();
            JOptionPane.showMessageDialog(this, "Guía Turístico creado con éxito","Correcto",JOptionPane.INFORMATION_MESSAGE);                
    }//GEN-LAST:event_btnAgregarGuiaActionPerformed

    private void btnCerrarGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarGuiaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarGuiaActionPerformed

    private void txtCalleGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleGuiaActionPerformed

    private void txtNumeracionGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeracionGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeracionGuiaActionPerformed

    private void txtCiudadGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadGuiaActionPerformed

    private void txtEdadGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadGuiaActionPerformed

    private void txtComunaGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComunaGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComunaGuiaActionPerformed

    private void txtNombreGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGuiaActionPerformed

    /**
     * Limpia todos los campos del formulario de ingreso de guía.
     */
    private void limpiar(){
        txtCalleGuia.setText("");
        txtComunaGuia.setText("");
        txtCiudadGuia.setText("");
        txtNumeracionGuia.setText("");
        txtNombreGuia.setText("");
        txtEdadGuia.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPane1;
    private javax.swing.JButton btnAgregarGuia;
    private javax.swing.JButton btnCerrarGuia;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCalleGuia;
    private javax.swing.JLabel labelCiudadGuia;
    private javax.swing.JLabel labelComunaGuia;
    private javax.swing.JLabel labelEdadGuia;
    private javax.swing.JLabel labelNombreGuia;
    private javax.swing.JLabel labelNumeracionGuia;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField txtCalleGuia;
    private javax.swing.JTextField txtCiudadGuia;
    private javax.swing.JTextField txtComunaGuia;
    private javax.swing.JTextField txtEdadGuia;
    private javax.swing.JTextField txtNombreGuia;
    private javax.swing.JTextField txtNumeracionGuia;
    // End of variables declaration//GEN-END:variables
}
