package UI;

import Data.GestorEntidades;
import Model.ExcursionCultural;
import Model.PaseoLacustre;
import Model.RutaGastronomica;
import Util.UtilServicioTuristico;
import javax.swing.JOptionPane;


public class FrameIngresarServicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameIngresarServicio.class.getName());
    private final GestorEntidades gestor;
    UtilServicioTuristico utilServicio = new UtilServicioTuristico();
    /**
     * Creates new form FrameIngresarServicio
     */
    public FrameIngresarServicio(GestorEntidades gestorEntidades){
        this.gestor = gestorEntidades;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        labelSeleccionarServicio = new javax.swing.JLabel();
        labelNombreServicio = new javax.swing.JLabel();
        labelDuracionServicio = new javax.swing.JLabel();
        labelCambiar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtNombreServicio = new javax.swing.JTextField();
        txtDuracionServicio = new javax.swing.JTextField();
        txtVariableServicio = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox<>();
        btnAgregarServicio = new javax.swing.JButton();
        btnCerrarServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear nuevo servicio");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Nuevo Servicio");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo Servicio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

        labelSeleccionarServicio.setText("Seleccionar");

        labelNombreServicio.setText("Nombre");

        labelDuracionServicio.setText("Duración hrs");

        labelCambiar.setText("Nro Paradas");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setText("Datos Servicio");

        txtNombreServicio.addActionListener(this::txtNombreServicioActionPerformed);

        txtDuracionServicio.addActionListener(this::txtDuracionServicioActionPerformed);

        txtVariableServicio.addActionListener(this::txtVariableServicioActionPerformed);

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ruta Gastronómica", "Paseo Lacustre", "Excursión Cultural" }));
        comboBox.addActionListener(this::comboBoxActionPerformed);

        jLayeredPane1.setLayer(labelSeleccionarServicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelNombreServicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelDuracionServicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labelCambiar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNombreServicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtDuracionServicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtVariableServicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(labelDuracionServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDuracionServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCambiar)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(labelNombreServicio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreServicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtVariableServicio, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(8, 8, 8)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(labelSeleccionarServicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSeleccionarServicio))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(9, 9, 9)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreServicio)
                    .addComponent(txtNombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuracionServicio)
                    .addComponent(txtDuracionServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCambiar)
                    .addComponent(txtVariableServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnAgregarServicio.setText("Agregar");
        btnAgregarServicio.addActionListener(this::btnAgregarServicioActionPerformed);

        btnCerrarServicio.setText("Cerrar");
        btnCerrarServicio.addActionListener(this::btnCerrarServicioActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarServicio)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrarServicio)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarServicio)
                    .addComponent(btnAgregarServicio))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreServicioActionPerformed

    private void txtDuracionServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionServicioActionPerformed

    private void txtVariableServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVariableServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVariableServicioActionPerformed

    private void btnAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioActionPerformed
        String opcion = comboBox.getSelectedItem().toString();
        String nombreServicio;
        double duracionServicio;

        switch(opcion)
        {
            case "Ruta Gastronómica":
                nombreServicio = txtNombreServicio.getText();
                int paradas;

                if(!utilServicio.EsDouble(txtDuracionServicio.getText()))
                {
                    return;
                }
                else if(!utilServicio.EsEntero(txtVariableServicio.getText()))
                {
                    return;
                }
                duracionServicio = Double.parseDouble(txtDuracionServicio.getText());                    
                paradas = Integer.parseInt(txtVariableServicio.getText());
                var rutaGastronomica = new RutaGastronomica(nombreServicio, duracionServicio, paradas);
                if(!utilServicio.ValidarServicio(rutaGastronomica)){
                    return;
                }
                gestor.agregar(rutaGastronomica);
                Limpiar();
                JOptionPane.showMessageDialog(this, "Ruta Gastronómica creada con éxito","Correcto",JOptionPane.INFORMATION_MESSAGE);                
                break;

            case "Paseo Lacustre":
                nombreServicio = txtNombreServicio.getText();
                var tipoEmbarcacion = txtVariableServicio.getText();
                if(!utilServicio.EsDouble(txtDuracionServicio.getText()))
                {
                    return;
                }               
                duracionServicio = Double.parseDouble(txtDuracionServicio.getText());                                    
                var paseoLacustre = new PaseoLacustre(nombreServicio, duracionServicio, tipoEmbarcacion);
                if(!utilServicio.ValidarServicio(paseoLacustre))
                {
                   return; 
                }
                gestor.agregar(paseoLacustre);
                Limpiar();
                JOptionPane.showMessageDialog(this, "Paseo Lacustre creado con éxito","Correcto",JOptionPane.INFORMATION_MESSAGE);                
                break;
                    

            case "Excursión Cultural":
                nombreServicio = txtNombreServicio.getText();
                var lugarHistorico = txtVariableServicio.getText();
                if(!utilServicio.EsDouble(txtDuracionServicio.getText()))
                {
                    return;
                }               
                duracionServicio = Double.parseDouble(txtDuracionServicio.getText());                                    
                var excursionCultural = new ExcursionCultural(nombreServicio, duracionServicio, lugarHistorico);
                if(!utilServicio.ValidarServicio(excursionCultural))
                {
                   return; 
                }
                gestor.agregar(excursionCultural);    
                Limpiar();
                JOptionPane.showMessageDialog(this, "Excursión cultural creada con éxito","Correcto",JOptionPane.INFORMATION_MESSAGE);                
                break;
        }
        
    }//GEN-LAST:event_btnAgregarServicioActionPerformed

    private void btnCerrarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarServicioActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarServicioActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        String opcion = comboBox.getSelectedItem().toString();

        switch(opcion)
        {
            case "Ruta Gastronómica":
                labelCambiar.setText("Nro. Paradas");                                
                break;

            case "Paseo Lacustre":
                labelCambiar.setText("Tipo Embarcación");
                break;

            case "Excursión Cultural":
                labelCambiar.setText("Lugar Histórico");
                break;
        }
    }//GEN-LAST:event_comboBoxActionPerformed

    private void Limpiar(){
    txtDuracionServicio.setText("");
    txtNombreServicio.setText("");
    txtVariableServicio.setText("");    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarServicio;
    private javax.swing.JButton btnCerrarServicio;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCambiar;
    private javax.swing.JLabel labelDuracionServicio;
    private javax.swing.JLabel labelNombreServicio;
    private javax.swing.JLabel labelSeleccionarServicio;
    private javax.swing.JTextField txtDuracionServicio;
    private javax.swing.JTextField txtNombreServicio;
    private javax.swing.JTextField txtVariableServicio;
    // End of variables declaration//GEN-END:variables
}
